### ISSUE TITLE
settle on conventions for versioning

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/styles#7]
We need to figure out our plan going forward for version-management vis-a-vis schema changes. Possible options:
1. ids are stable across versions, and so versioning happens with git branching
2. ids are tied to versions, and so versioning happens via structure of directories in repositories; e.g. `http://citationstyles.org/styles/1.1/apa.csl`.

**Comment by bwiernik** [comment]
@adam3smith I think this is resolved now with the versioned repo branches?

**Comment by adam3smith** [comment]
I'm fine with what we have, but I'm not sure it actually fixes the issues raised above? E.g still not clear how the 1.0.2 version of APA (e.g.) is uniquely identified

**Comment by bwiernik** [comment]
Wouldn't that be identified by the repo branch it's retrieved from rather than in the style itself?

**Comment by adam3smith** [comment]
My understanding from Simon's point above is that ideally this would be in the style so that self link (or URI) resolve uniquely e.g. for a dependent style, but I think having implementations commit to a branch is acceptable as a solution, so I'm fine with keeping this closed.
