### ISSUE TITLE
APA: Add disambiguation letter to publication date even if original published date is distinct

### ISSUE THREAD

**Issue by dharmababa** [citation-style-language/styles#7667]
Issue verified in Zotero 7.0.22

If multiple sources from the same author have the same published date, a letter is only added to disambiguate the date if the originally published date is also different. 

For example for 3 different essays from the same author, Zotero inserts in-text citations (and corresponding reference entries) as:
(1926/1967a)
(1926/1967b) -- different essay but same original AND publish date
(1927/1967) -- different essay but different original date so no letter added

The in-text citations should be:

(1926/1967a)
(1926/1967b)
(1927/1967c)

This allows the reader to quickly look up the correct reference without having to look at the "Original work published..." note at the end of the reference for each.

The correct behavior was confirmed to my copy editor by the APA (SJournalsStyleExpert@apa.org), citing section 8.15. I can share the email thread if needed.

https://forums.zotero.org/discussion/124486/apa7-add-letter-to-publication-date-even-if-originally-published-date-is-different#latest

**Comment by bwiernik** [comment]
Thanks for the flag. This is fixed in the major update to APA styles by @dunning. I hope to have time to review and merge them this month

**Comment by adam3smith** [comment]
As I noted on the Zotero forums, I don't think this can be fixed with current CSL (which implicitly relies on `disambiguate="true"` for the year suffixes). Items with different original date are not ambiguous in text, so they don't get the year suffix. I have verified that Andrew's APA update has the same behavior that's reported here (example quickly constructed to have the right logic; work doesn't actually exist as cited).

<img width="809" height="207" alt="Image" src="https://github.com/user-attachments/assets/18f2db44-f909-43bd-bd2e-d885068e1343" />

Note this is also following the text of the specs which has this for `disambiguate-add-year-suffix`:
> If set to “true” (“false” is the default), an alphabetic year-suffix is added to **ambiguous cites**

This would require both a spec and a processor change and the behavior here wouldn't be easy to describe to accommodate all different desirable behaviors.

**Comment by charlesjmorris** [comment]
> This would require both a spec and a processor change and the behavior here wouldn't be easy to describe to accommodate all different desirable behaviors.

Thank you for the detailed reply and confirmation that Andrew's update didn't fix (as I observed as well). Is there anywhere the spec/processor change that you mention could be tracked so this isn't lost?

**Comment by bwiernik** [comment]
I'm the principal maintainer of the APA CSL styles. I'm personally very skeptical of this rule from APA. If the original date is shown, the citation is no longer ambiguous. APA is unique in its call for disambiguation here. It would require major updates to processor logic to make this change possible, and I don't see that happening in the short term.

**Comment by adam3smith** [comment]
I think APA's treatment of original dates is a bit weird, but given how they're displayed in the bibliography (i.e. with the original date at the end of the citation), the rule makes sense to me: only with the suffix can you immediately identify the entry matching a citation based on the first elements in the bibliography. 
There have also been some other edge cases wrt disambiguation, for example disambiguate evaluating to false when cross references (via first-reference-note-number) are added to citations, we might be able to address these with the same update. Not trivial, but we might at least track it over on the schema tracker, I'll create a ticket there (which is no guarantee we'll implement it and certainly not that it'll happen any time soon).

**Comment by adam3smith** [comment]
https://github.com/citation-style-language/schema/issues/452
